### ISSUE TITLE
issue with callbacks and latest fsspec

### ISSUE THREAD

**Issue by fnattino** [NLeSC-GO-common-infrastructure/dcachefs#19]
The following snippet:
```python
import dcachefs
import fsspec

fs = fsspec.filesystem("dcache")
fs.put(lpath="./EXAMPLE_SOURCE_FILE", rpath="/pnfs/grid.sara.nl/data/remotesensing/disk/EXAMPLE_DEST_FILE")
```

Raises the following issue with `fsspec==2024.5.0`, but it works fine with `fsspec==2023.12.2`:
```
Traceback (most recent call last):
  File "/gpfs/work2/0/ttse0619/francesco/Projects/RS-DAT/tmp.py", line 5, in <module>
    fs.put(lpath="/gpfs/work2/0/ttse0619/DAT_data/EU/all_data_2014-1-31_2014-02-10_EU.zarr/.zmetadata", rpath="/pnfs/grid.sara.nl/data/remotesensing/disk/EcoExtreML/EU/tmpfile")
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/asyn.py", line 589, in _put
    return await _run_coros_in_chunks(
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/asyn.py", line 268, in _run_coros_in_chunks
    result, k = await done.pop()
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/asyn.py", line 245, in _run_coro
    return await asyncio.wait_for(coro, timeout=timeout), i
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/fsspec/callbacks.py", line 81, in func
    return await fn(path1, path2, callback=child, **kwargs)
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/dcachefs/dcachefs.py", line 363, in _put_file
    r = await session.put(url, data=fd, **request_kwargs)
  File "/gpfs/home2/fnattino30/mambaforge/envs/dcachefs/lib/python3.10/site-packages/aiohttp/client.py", line 1014, in put
    self._request(hdrs.METH_PUT, url, data=data, **kwargs)
TypeError: ClientSession._request() got an unexpected keyword argument 'callback'
```

**Comment by fnattino** [comment]
Solved by #24
